# OpenGraph / Twitter metadata
title: Joint Travel Regulations (Prototype)
small_title: Joint Travel Regulations (Prototype)
smallest_title: JTR (Prototype)
description: This is a prototype for an online version of the Joint Travel Regulations for the Defense Travel Management Office
name: Joint Travel Regulations (Prototype)
report_url: https://federalist-docs.18f.gov/assets/Federalist-Compliance-Memo.pdf


# GA and GitHub data

repo: https://github.com/18F/dtmo-jtr-prototype
org_name: 18f
repo_name: federalist-report-template
uswds_path: assets/vendor/uswds

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor
- gulpfile.js
- manifest.yml
- package.json
- Staticfile
- Staticfile.auth
- node_modules
- .nvmrc
- .sass-cache
- todo.txt
- assets/sass


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/
