# OpenGraph / Twitter metadata
title: Title of report
small_title: Title of report
smallest_title: Title of report
description: This is a description.
name: Title of report
report_url: https://federalist-docs.18f.gov/assets/Federalist-Compliance-Memo.pdf


# GA and GitHub data

repo: https://github.com/18f/federalist-report-template/

uswds_path: assets/vendor/uswds

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor
- gulpfile.js
- manifest.yml
- package.json
- Staticfile
- Staticfile.auth
- node_modules
- .nvmrc
- .sass-cache
- todo.txt
- assets/sass


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/
